# Generated by Django 3.2.4 on 2021-06-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('range_from', models.IntegerField(blank=True, null=True)),
                ('range_to', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('column_type', models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], default='Text', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('row', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], default=',', max_length=10)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], default='"', max_length=10)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
